<x-app-layout>
    <x-slot name="header">
        <div class="flex">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight flex-initial">
                {{ __('Node Dashboard') }}
            </h2>
            <form class="flex-initial" action="{{route('catalog.show',[$id_node])}}">
                <p><button class="btn-main" type="submit">Watch catalog</button>
                </p>
            </form>
            <form method="post" action="{{route('goods.destroy',[$good->id])}}">
                {{csrf_field()}}
                {{method_field('delete')}}
                <input type="submit" value="Delete Good" class="btn-del">
            </form>
        </div>
    </x-slot>
    <div class="container mx-auto px-4 p-6 ">
        <table>
            <tbody>
                @if(!empty($good))
                <tr>
                    <th>Id</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->id))
                        <p class="bg-success">{{$good->id}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Art</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->art))
                        <p class="bg-success">{{$good->art}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Url</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->url))
                        <p>{{$good->url}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Name</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->name))
                        <p>{{$good->name}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Price</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->price))
                        <p>{{$good->price}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Store</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->store))
                        <p>{{$good->store}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Description txt</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->descripttxt))
                        <p>{{$good->descripttxt}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Description html</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->descripthtml))
                        <p>{{$good->descripthtml}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Fotos</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->fotos))
                        <p>{{$good->fotos}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Videos</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->videos))
                        <p>{{$good->videos}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Charecteristics</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->charact))
                        <p>{{$good->charact}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Complectation</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->complect))
                        <p>{{$good->complect}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Filter1</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->f1))
                        <p>{{$good->f1}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Filter2</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->f2))
                        <p>{{$good->f2}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Filter3</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->f3))
                        <p>{{$good->f3}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Filter4</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->f4))
                        <p>{{$good->f4}}</p>
                        @endif
                    </td>
                </tr>
                <tr>
                    <th>Filter5</th>
                </tr>
                <tr>
                    <td>
                        @if(!empty($good->f5))
                        <p>{{$good->f5}}</p>
                        @endif
                    </td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
</x-app-layout>